version: "1.0"

server:                           ## [] rdf:type fuseki:Server ;
  name: "Fuseki server 1"
  port: 3131                      ## Smart Cache Graph:: port is decided elsewhere but implement field "port"
  ## Settings possible here
  ## Need to make a Turtle () list.

## This is a list of 2 fuseki:Service
services:
  ## First fuseki:Server -- this will be "service1", a generated name, in config.ttl
  - name: "/ds"                                  ## fuseki:name "/ds2"
    endpoints:
      ## This endpoint is just an operation
      - operation: query
      ## Another entry in the endpoint YAML list
      - name: "sparql"
        operation: query                         ##  fuseki:operation fuseki:query ;
        settings:
          'arq:queryTimeout': "1000,10000"
      ## 3rd operation
      - name: "data-update"
        operation: update
    database:  "mem-db"                          ##  fuseki:dataset :dataset1 named as the storage. "mem-db"

  ## Second fuseki:Server
  ## This is service 2.
  - name: "/db2"
    endpoints:
      - name: "sparql"
        operation: query                         ##  fuseki:operation fuseki:query ;
    database : "tdb2-db" 


# Storage. "name" are used to connect "database:" in the service to a declaration
## Replace the name with a URI and ise 

databases:
  - name: "mem-db"
    db-type: TIM                                   ## rdf:type ja:MemoryDataset

  - name: "tdb2-db"
    db-type: TDB2                                  ## rdf:type  tdb2:DatasetTDB2
    location: "DB2"                                ## tdb2:location "DB2"
    settings:
      'tdb2:unionDefaultGraph': true             ## tdb2:unionDefaultGraph true
